### PR TITLE
Fix error (SlimSelect is not a constructor error.)

### PR DESCRIPTION
**Pull request by AzA-95**
This pr fix this issue https://github.com/brianvoe/slim-select/issues/435
And this https://github.com/brianvoe/slim-select/issues/443

### CODE REVIEW

**Comment by brianvoe** [comment]
Ill do a release once the other pr is resolved. https://github.com/brianvoe/slim-select/issues/443#issuecomment-1457899220

**Comment by AzA-95** [comment]
You can merge this changes :)
In that comment https://github.com/brianvoe/slim-select/issues/443#issuecomment-1457899220 I meant while before my [PR ](https://github.com/brianvoe/slim-select/pull/446) is merged use that code in comments :)

**Comment by AzA-95** [comment]
This pr https://github.com/brianvoe/slim-select/pull/445 is not actual because changes for fix the error need only on **package.json**
Because webpack vite and other bundlers use package.json for path the module file when import module so
**import SlimSelect from 'slim-select'**

**Comment by AzA-95** [comment]
> This pr https://github.com/brianvoe/slim-select/pull/445 is not actual because changes for fix error https://github.com/brianvoe/slim-select/issues/429 need only on package.json

The current Pr fix the error correct, changing only file  **package.json**

**Comment by brianvoe** [comment]
ok ill get a release for it out today

**Comment by garrywilliams** [comment]
Thanks and that works for me. 

Note: I am using Rails 7 and when I use the `bin\importmap pin` command it pins "slim-select" to the 2.4.3/dist/slimselect.umd.js. I then still get the error:
Uncaught SyntaxError: The requested module 'slim-select' does not provide an export named 'default'

However, if I change my `importmap.rb` to use 2.4.3/dist/slimselect.es.js then it all works correctly

**Pull request merged**
