### PR TITLE
restore style inheritance from original select

### LINKED ISSUE #412: Select inline styles
**Describe the bug**
The inheritance of the inline styles of the `select` seems to be broken. 

**Screenshots**
From the docs:
image

### PR DESCRIPTION
**Pull request by gmq**
fixes #412

main use case for me is setting a width to the original select and have it respect that

### CODE REVIEW

**Comment by brianvoe** [comment]
I completely understand this pr, unfortunately it has adverse reactions. If you would like the styles applied to the original select I suggest doing it on destroy when the original select returns. Let me know your thoughts.

**Comment by gmq** [comment]
Sorry, I meant applying the style that the original select has to the slim-select div when initializing. Without this fix, it ignores the inline styles.

**Comment by brianvoe** [comment]
Let me play around with this and ill get back to you if I find anything.

**Comment by brianvoe** [comment]
I dont see anything wrong happening. I get this merged in. I hope this doesnt effect anyone

**Comment by brianvoe** [comment]
v2.4.3

**Pull request merged**
