### PR TITLE
Do not replace id of original select

### PR DESCRIPTION
**Pull request by coolibry**

### CODE REVIEW

**Comment by brianvoe** [comment]
Im a bit conflicted with this one. I understand not wanting to alter the id on the slim select render. But if one isnt set then I do want to set it to the generated id otherwise I want to set the main settings to the id that was on the original select. Just dont need to update it again after its already been established.

**Comment by brianvoe** [comment]
The original problem is that we shouldnt be overriding the id with something else. If an ID is already set on the original select then just make that the settings ID the one from the original select thus keeping 1 general id between everything.

**Comment by coolibry** [comment]
this is a good way, but this PR is not valid for this solution.

**Comment by brianvoe** [comment]
v2.3.1

**Pull request merged**
