### PR TITLE
Add option searchFocus

### PR DESCRIPTION
**Pull request by Fudoshiki**
Allow to disable search input focus when opening select

### CODE REVIEW

**Comment by brianvoe** [comment]
Can you describe what issue your trying to solve?

**Comment by Fudoshiki** [comment]
When open select on mobile, it will activate keyboard, i don't want it

**Comment by 2x2p** [comment]
hint: making the input readonly before it receives focus will block the on screen keyboard on iOS. then a click event should remove the readonly state and do element.blur() and again element.focus() to get back to normal behaviour. This is a workaround to make sure the user intended to enter the input element. However this will not allow entry by tab key.

**Comment by Fudoshiki** [comment]
I tried search.input.blur() in beforeOpen/afterOpen but it adds a lag when list is opening on low end phones
The option allows you to simply not call the focus() without any loss of performance and additional hacks

**Comment by 2x2p** [comment]
probably you are testing on an older OS version? I just tried it on some devices, none of them auto open the keyboard unless I manually touch the search field. Give Brian more details else it’s hard to reproduce your case.

**Comment by brianvoe** [comment]
I hear your situation and i think the pr you submitted would work. I am just trying to figure out if there is an easier way to tackle the issue without having to add another option. Cause the only issue i have is what do we do when on mobile and you want to search and need the keyboard to pop up.

**Comment by Fudoshiki** [comment]
**2x2p**'s solution works fine, but in big forms we need add many event listeners

On cheap android phones it's lagged, we need listening for each search input and call blur() on opening list, this adds a delay on low cost phones

I can add listener on **beforeOpen** and remove on **afterOpen**, but it's also micro lag on opening animation

With option works smoothly without performance issue

**Comment by Fudoshiki** [comment]
I set **readonly** all search inputs on **slimselect** initialization, but i don't like idea to
adding an event listener for each search input

**Comment by brianvoe** [comment]
I understand where your going with this but the underlyning issue is if someone is on mobile dont pop open the keyboard. and this doesnt specifically solve that issue without forcing someone to code looking for whether they are on mobile or not. I still think the best solution to this is having slim select check if they are on mobile and if so not focusing on the input field. All doable with adding another settings option.

**Comment by Fudoshiki** [comment]
@brianvoe I need to turn off the focus when opening the select on any devices (desktop and mobile)
@2x2 offered a solution, I wrote the answer to it

In my case, the focus turned off is a very convenient solution, when the user clicks on the select input, he can immediately select the option with the arrow keys on desktop, on mobile this doesn't activate keyboard

Option is the simplest and most performance efficient solution

**Comment by brianvoe** [comment]
Sorry for the delay on this. Im going to merge this into develop and do a release soon. Im trying to be lean on this package given the name is slim select and over the years I have added a bunch of options and it becomes less and less slim. But at this point its fine. Im going to try to do a release tonight.

**Comment by Fudoshiki** [comment]
Thank you!

**Pull request merged**
