### PR TITLE
Fix display allways true

### PR DESCRIPTION
**Pull request by Aurimas1**

### CODE REVIEW

**Comment by Aurimas1** [comment]
I had further investigation I saw that this property is unused. So probably I overlook. So can you give a location?

**Comment by brianvoe** [comment]
Sorry i dont understand. what do you mean "can you give a location"

**Comment by Aurimas1** [comment]
I didn't find any place(in code) where this variable was used.

**Comment by brianvoe** [comment]
Its a used select option

**Comment by Aurimas1** [comment]
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/data.ts#L18
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/data.ts#L51
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/data.ts#L65
So in all cases you assign this variable/property, but never used or I miss a place?

**Comment by brianvoe** [comment]
You might be correct it may be a loose variable that had a purpose but wasnt fully used.

**Pull request merged**
