### PR TITLE
Fix #429

### LINKED ISSUE #429: [ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"
I have problem with SlimSelect version: ^2.4.0
Not have problem with version 2.3.3

```
[ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"

      4 │ import SlimSelect from 'slim-select';
        ╵        ~~~~~~~~~~
```

Thanks and regards
Francesco

### PR DESCRIPTION
**Pull request by francesco-loreti**

### CODE REVIEW

**Comment by brianvoe** [comment]
Unfortunately this isnt a proper fix as it alters the dist which is auto generated.

**Comment by brianvoe** [comment]
If you can get it part of the build process, Ill get it merged in.

**Comment by AzA-95** [comment]
This PR is not actual, you can close it. 
I sent https://github.com/brianvoe/slim-select/pull/446 pr for fix this issue https://github.com/brianvoe/slim-select/issues/429 too

In the current Pr is code incorrect. Beacause has code **export default SlimSelect;** in slimselect.umd.js and slimselect.js
The code **export default SlimSelect;** is es6 feature and this code shouldn't be in files slimselect.umd.js and slimselect.js because the files  slimselect.umd.js and slimselect.js used for browser which might be not suported es6 feauture

The corect file for the code **export default SlimSelect;** is slimselect.es.js and this file https://github.com/brianvoe/slim-select/pull/445/commits/761f8dbce17d0316eb3591d82aec3dd514c91425 has the code **export default SlimSelect;**

**Comment by brianvoe** [comment]
Im looking for someone who knows rollup well enough to make config changes to fix any of these build output issues. If you want any of them fixed please submit a pr make those rollup changes.

**Comment by AzA-95** [comment]
I sent Pr https://github.com/brianvoe/slim-select/pull/446 for fix this issue. After merged this pr the code will be work correct. Tested in webpack 5 and Vite and also should work corect in rollup

**Comment by brianvoe** [comment]
ok ill get a release for it out today

**Pull request closed without merging**
