### PR TITLE
Expose styles for bundlers to inline css

### PR DESCRIPTION
**Pull request by dankrajnak**
Happy to update documentation if need be as well -- just can't use this in my project currently as I need to inline the css in my js bundle.  I think this could make it easier.

### CODE REVIEW

**Comment by brianvoe** [comment]
Ill get this in as soon as possible

**Comment by dankrajnak** [comment]
@brianvoe thanks so much!  Any timeline on this?  Let me know if I can help.

**Comment by dankrajnak** [comment]
@brianvoe just want to bring attention back to this.  Let me know if there's anything I can do.

**Comment by brianvoe** [comment]
sorry for the delay v2.5.1

**Pull request merged**
