### PR TITLE
Add ability to change the default deselect/delete text from 'x' to something else.

### PR DESCRIPTION
**Pull request by antony**

### CODE REVIEW

**Comment by brianvoe** [comment]
I see no reason not to add this in. Seems simple enough. Can you give me some background and usage for what your using it for? I just want to make sure we cover our bases.

**Comment by antony** [comment]
Sure. I'm building https://github.com/beyonk-adventures/svelte-slim-select
which wraps your module in a way convenient for integrating into
svelte/sapper applications.

The eventual goal is using the component as part of our search on
https://beyonk.com - the letter 'x' as a delete icon isn't really cutting
it for our designers, so I'm switching it out for a small utf8 cross symbol.

Thanks for a great module!

**Comment by brianvoe** [comment]
Ok sounds good. Ill get this in sometime in the morning.

**Comment by brianvoe** [comment]
So sorry for not getting this in earlier. you did such a great job getting this in and i totally dropped the ball. Im going to merge this into develop and run this locally to make sure everything works. then get it into a release today.

**Pull request merged**
