### PR TITLE
Added option to add the select content directly to the body

### PR DESCRIPTION
**Pull request by stefan-lacatus**
Added a new option called `addToBody`
This causes the dropdown content to be added directly to the document body, rather than the parent container.
This allows using slim-select in scenarios where you have no control of the overflow state of the parent containers, and would fix issues like #95 or #136.

### CODE REVIEW

**Comment by brianvoe** [comment]
I love this option. How well did you test this will all of the possible options that where in slim select?

**Comment by stefan-lacatus** [comment]
I've tested a bit, by updating all the slim-selects on the options page to use `addToBody` as well as within our app. I didn't see any issues. However, more proper testing will be done next week.

**Comment by brianvoe** [comment]
ok ill pull this in and test as much as i can and see if we can get this in soon.

**Comment by brianvoe** [comment]
v1.24.0 nice job on this!!!

**Pull request merged**
