### PR TITLE
Avoid trigger 2x afterChange

### PR DESCRIPTION
**Pull request by coolibry**

### CODE REVIEW

**Comment by brianvoe** [comment]
I was hoping to not have to add another parameter. But I think this is probably the best way to tackle the issue.

**Comment by coolibry** [comment]
yes the only other way is to remove line afterChange at render.ts
i can make a PR if you want.

**Comment by brianvoe** [comment]
I think a secondary runAfterChange works. Cause I also have to deal with setting select in lets say the vue component and it would be nice to know whether or not to trigger afterChange.

**Comment by brianvoe** [comment]
v2.3.1

**Pull request merged**
