### PR TITLE
React integration 357

### PR DESCRIPTION
**Pull request by dminkovski**
[React integration #357
](https://github.com/brianvoe/slim-select/issues/357)

Hey @brianvoe 😄 
so the React integration part was pretty intuitive and straight-forward thanks to your great build!

Unfortunately I am struggling at including it into the Vue Doc App > frameworks page.
Though I am sure there is a cleaner and better solution, I have currently setup a hacky way currently to get it working:

1. Include the react render component script (with ReactDOM.createRoot) in the main index.html.
2. Add a query and timeout into the doc and render into a predefined ID.

Maybe you can help me with this part before moving forward? 

Also feel free to have a look at the react code and let me know what you think!
I will gladly update it.

### CODE REVIEW

**Comment by brianvoe** [comment]
Hey! Sorry for the delay on this I checked out the pr and the code looks good. Because I have decided not to use react as my primary framework I dont know how much help i would be in getting react working within the docs.

What is your current status on getting react working in the docs? If your stuck on something I can give it a try.

**Comment by dminkovski** [comment]
Hey! No worries 👍  I do enjoy both Vue and React 😄 
So the deal is - it essentially works but it is not clean:

I tried to use several libraries to convert the react component into a vue one to be able to use it, but I could not find a working solution yet.
Therefore I do not know a way to include the React component in the docs the "vue way".
What I did to solve this problem was to include the react component in the index.html of the docs -> then it gets rendered into the vue doc application based on a react dedicated div. 

Thus if you want to change the way the react component gets shown you need to change that in the react application "frameworkpage.tsx". This means if we want to add more examples of usage like in the vue doc - we need to create multiple react pages (one for each example) or have the entire part of the doc (examples, texts) being in the react application itself.

Please let me know which way you like more.
1. Have one example.tsx in the react folder for each documentation example used in the doc app (vue) -> will need to add multiple LINKS in the HTML to the react examples.
2. Have all the text and examples in ONE doc.tsx  -> ONE Link in the HTML

This can be a bit confusing - let me know if you prefer a call or something 😄

**Comment by brianvoe** [comment]
I think what your saying makes sense to me. I don't think its that dirty if I am thinking about what you are saying correctly. If you have something I can run to see it in action I can give you my thoughts on it more precisely.

**Comment by dminkovski** [comment]
It’s already in the PR :) you should be able to run it. Please let me know if you face any issues.

**Comment by brianvoe** [comment]
ok thanks ill pull it today and let you know my thoughts once i get a chance to play with it.

**Comment by brianvoe** [comment]
Ok i got a sec to pull your pr down and look at it. I think. given that its a completely different framework what you wrote I think is perfect.

Some adjustments I would make before I merge it in
1. Move the react dependencies and devdependencies into the main package.json file just so when people npm install they can do it on the main root and also we wont have to deal with duplicate dependencies.
2. I would seperate vue and react into completely different pages. You can move vue and react to the main menu if you think that makes the most sense.
3. Add react to the main package.json workspace.
4. Just a few other examples of usage like the vue has(if you feel like its needed)

Other than that did you find any limitation issues like i did with vue integration not being able to use dynamic options?

Nice job! I look forward to merging this in.

**Comment by dminkovski** [comment]
I did add some examples and tried to do the changes you asked for.
Please check if that is what you meant :) 
Also I am not sure about the build itself. I might need some input/help from you, if you do not mind.

Looking forward to hearing from you!

**Comment by brianvoe** [comment]
Hey I want to take another shot at getting this in. Im going through issues and pr now and doing some updates. let me know if you can resolve the conflicts and ill try to get it in.

**Pull request merged**
